# Generated by Django 4.2.15 on 2024-08-21 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_subdescription_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sub_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='SubDescription',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
