# Generated by Django 4.2.15 on 2024-08-21 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('RX', 'RX'), ('OTC', 'OTC')], max_length=3)),
                ('unit', models.CharField(max_length=50)),
                ('potency', models.CharField(max_length=50)),
                ('sub_description', models.TextField(blank=True, null=True)),
                ('how_to_use', models.TextField(blank=True, null=True)),
                ('side_effects', models.TextField(blank=True, null=True)),
                ('drug_interactions', models.TextField(blank=True, null=True)),
                ('precautions', models.TextField(blank=True, null=True)),
                ('additional_labels', models.JSONField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('sale', models.BooleanField(default=False)),
                ('top_selling', models.BooleanField(default=False)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sell_price_inr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sell_price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
            ],
        ),
    ]
