# Generated by Django 4.2.15 on 2024-08-21 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_category_product_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='additional_labels',
        ),
        migrations.CreateModel(
            name='ProductLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='store.product')),
            ],
        ),
    ]
