# Generated by Django 4.2.15 on 2024-08-21 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_unit_alter_product_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUnitDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potency', models.CharField(max_length=50)),
                ('price_inr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_details', to='store.product')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.unit')),
            ],
            options={
                'unique_together': {('product', 'unit', 'potency')},
            },
        ),
    ]
