# Generated by Django 4.2.15 on 2024-08-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_productunitdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='potency',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=50),
        ),
        migrations.AlterField(
            model_name='productunitdetail',
            name='potency',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
