# Generated by Django 4.2.15 on 2024-08-22 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_potency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_flag', models.ImageField(upload_to='flags/')),
                ('rx_required', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potency', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_inr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('country_of_origin', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='potency',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sell_price_inr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sell_price_usd',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.DeleteModel(
            name='ProductUnitDetail',
        ),
        migrations.AddField(
            model_name='variant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product'),
        ),
        migrations.AddField(
            model_name='variant',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.unit'),
        ),
        migrations.AddField(
            model_name='countrydetail',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_details', to='store.variant'),
        ),
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together={('product', 'unit', 'potency', 'country_of_origin')},
        ),
    ]
