# Generated by Django 4.2.15 on 2024-08-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_countrydetail_variant_remove_product_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='number_of_tablets',
            field=models.IntegerField(default=1),
        ),
    ]
