# Generated by Django 4.2.15 on 2024-08-22 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_variant_number_of_tablets'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryOfOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='variant',
            name='country_of_origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.countryoforigin'),
        ),
    ]
