# Generated by Django 4.2.15 on 2024-08-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_variant_country_of_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='country_of_origin',
            field=models.CharField(max_length=255),
        ),
    ]
