# Generated by Django 4.2.15 on 2024-08-22 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_variant_country_of_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='country_of_origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.countryoforigin'),
        ),
    ]
