# Generated by Django 4.2.15 on 2024-08-24 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_cart_updated_at_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='updated_at',
        ),
    ]
