# Generated by Django 4.2.15 on 2024-08-24 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_remove_cart_created_at_remove_cart_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='variant',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
