# Generated by Django 4.2.15 on 2024-08-26 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_address_billinginfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinginfo',
            name='billing_address',
        ),
    ]
