# Generated by Django 4.2.15 on 2024-08-28 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_alter_cart_session_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingInfo',
        ),
    ]
