# Generated by Django 4.2.15 on 2024-08-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_rename_address_line1_address_address_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('PRICE', 'Fixed Price'), ('PRODUCT', 'Product-Based')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='discounts',
            field=models.ManyToManyField(blank=True, to='store.discount'),
        ),
    ]
