# Generated by Django 4.2.15 on 2024-08-28 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_discount_product_discounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discounts',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
