# Generated by Django 4.2.15 on 2024-08-29 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
