# Generated by Django 4.2.15 on 2024-08-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='variants',
            field=models.ManyToManyField(through='store.OrderItem', to='store.variant'),
        ),
    ]
