# Generated by Django 4.2.15 on 2024-08-29 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_order_variants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='variants',
        ),
        migrations.AddField(
            model_name='order',
            name='variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.variant'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
