# Generated by Django 4.2.15 on 2024-08-29 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_shipping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='Shipping',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.shipping'),
        ),
    ]
