# Generated by Django 4.2.15 on 2024-08-29 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_remove_order_address_order_shipping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Shipping',
            new_name='shipping_address',
        ),
    ]
