# Generated by Django 4.2.15 on 2024-08-29 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0054_discountcode_discount_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reordered_at', models.DateTimeField(auto_now_add=True)),
                ('new_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_origin', to='store.order')),
                ('original_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorders', to='store.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.variant')),
            ],
        ),
    ]
