# Generated by Django 4.2.15 on 2024-08-29 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_reorder_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reorder',
            old_name='reordered_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='reorder',
            name='new_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reordered_from', to='store.order'),
        ),
    ]
