# Generated by Django 4.2.15 on 2024-09-03 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0061_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
