# Generated by Django 4.2.15 on 2024-09-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0063_alter_review_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
