# Generated by Django 4.2.15 on 2024-09-05 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0073_alter_chatmessage_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='sender',
            new_name='sender1',
        ),
    ]
