# Generated by Django 4.2.15 on 2024-09-05 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0074_rename_sender_chatmessage_sender1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender1',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender2',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
