# Generated by Django 4.2.15 on 2024-09-05 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0078_alter_chatmessage_sender_alter_chatmessage_session'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
