# Generated by Django 4.2.15 on 2024-09-05 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0079_delete_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatRequest',
        ),
    ]
