# Generated by Django 4.2.15 on 2024-09-05 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0088_ticketreply_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketreply',
            name='user',
        ),
    ]
