# Generated by Django 4.2.15 on 2024-09-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0089_remove_ticketreply_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='tickets/attachments/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='deparment',
            field=models.CharField(default='', max_length=20),
        ),
    ]
