# Generated by Django 4.2.15 on 2024-09-09 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0092_ticketagent_ticketreply_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
                ('delivery_time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HealthInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Weight (lbs)')),
                ('sex_of_patient', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, verbose_name='Sex of Patient')),
                ('is_breastfeeding', models.BooleanField(blank=True, null=True, verbose_name='Are you breastfeeding?')),
                ('is_smoker', models.BooleanField(blank=True, null=True, verbose_name='Is the patient a smoker?')),
                ('drug_allergies', models.BooleanField(blank=True, null=True, verbose_name='Any drug allergies?')),
                ('list_of_allergies', models.TextField(blank=True, null=True, verbose_name='List of Allergies')),
                ('prescription_list', models.TextField(blank=True, null=True, verbose_name='Prescription and Supplements List')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
