# Generated by Django 4.2.15 on 2024-09-09 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0093_shippingmethod_healthinformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthinformation',
            name='is_breastfeeding',
        ),
        migrations.RemoveField(
            model_name='healthinformation',
            name='is_smoker',
        ),
        migrations.RemoveField(
            model_name='healthinformation',
            name='list_of_allergies',
        ),
        migrations.RemoveField(
            model_name='healthinformation',
            name='prescription_list',
        ),
        migrations.RemoveField(
            model_name='healthinformation',
            name='sex_of_patient',
        ),
        migrations.RemoveField(
            model_name='shippingmethod',
            name='description',
        ),
        migrations.RemoveField(
            model_name='shippingmethod',
            name='method_name',
        ),
        migrations.AddField(
            model_name='healthinformation',
            name='allergies_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthinformation',
            name='breastfeeding',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthinformation',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='healthinformation',
            name='smoker',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthinformation',
            name='supplements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='name',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='healthinformation',
            name='drug_allergies',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthinformation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='healthinformation',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
