# Generated by Django 4.2.15 on 2024-09-09 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0094_remove_healthinformation_is_breastfeeding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='health_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.healthinformation'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.shippingmethod'),
        ),
    ]
