# Generated by Django 4.2.15 on 2024-09-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0095_order_health_info_order_shipping_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthinformation',
            name='weight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
