# Generated by Django 4.2.15 on 2024-09-09 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0098_alter_healthinformation_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthinformation',
            name='order',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='health_info', to='store.order'),
        ),
    ]
