# Generated by Django 4.2.15 on 2024-09-09 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0101_alter_healthinformation_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthinformation',
            name='order',
        ),
        migrations.AddField(
            model_name='healthinformation',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='health_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.healthinformation'),
        ),
    ]
