# Generated by Django 4.2.15 on 2024-09-10 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0107_alter_invoice_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='variant',
        ),
    ]
