# Generated by Django 4.2.15 on 2024-09-13 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0111_variant_original_price_usd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='original_price_usd',
        ),
    ]
