# Generated by Django 4.2.15 on 2024-09-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0112_remove_variant_original_price_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='original_price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
