# Generated by Django 4.2.15 on 2024-09-18 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0113_variant_original_price_usd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
