# Generated by Django 4.2.15 on 2024-10-07 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0114_remove_cartitem_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together=set(),
        ),
    ]
