# Generated by Django 4.2.15 on 2024-10-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0115_alter_variant_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
