# Generated by Django 4.2.15 on 2024-10-11 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0116_product_brand_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountcode',
            name='used_count',
        ),
    ]
