# Generated by Django 4.2.15 on 2024-10-16 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0121_alter_chatrequest_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrequest',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chat_requests', to='store.agent'),
            preserve_default=False,
        ),
    ]
