# Generated by Django 4.2.15 on 2024-10-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0124_remove_agent_user_agent_password_agent_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
