# Generated by Django 4.2.15 on 2024-10-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0126_chatrequest_guest_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrequest',
            name='guest_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chatrequest',
            name='guest_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
