# Generated by Django 4.2.15 on 2024-10-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0127_chatrequest_guest_name_chatrequest_guest_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
