# Generated by Django 4.2.15 on 2025-02-04 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0129_product_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='variant',
        ),
    ]
