# Generated by Django 4.2.15 on 2025-02-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0131_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='shipping_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
