# Generated by Django 4.2.15 on 2025-02-05 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0133_orderlabellink_order_carrier_order_tracking_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='carrier',
        ),
    ]
