# Generated by Django 4.2.15 on 2025-02-27 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0135_faq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
